version: "3"

services:
  tracker:
    image: nkijak/departure-vision-recorder
    volumes:
      - raw-storage:/usr/src/app/dv_data
    depends_on:
      - couchdb
    environment:
      - DB_HOST=couchdb
    
  couchdb:
    image: couchdb:1.6
    volumes:
      - logs:/usr/local/var/log/couchdb
      - db-data:/usr/local/var/lib/couchdb

volumes:
  raw-storage:
  logs:
  db-data:

